jobs: 
  - job: Build
    steps:
     - task: PowerShell@2
       enabled: true
       displayName: "Install dependencies"
       inputs:
         targetType: 'inline'
         script: 'npm ci'
         workingDirectory: tests/ # update accordingly

     - task: AzureCLI@2
       displayName: Run Playwright Test  
       env:
         PLAYWRIGHT_SERVICE_URL: $(PLAYWRIGHT_SERVICE_URL)
         PLAYWRIGHT_SERVICE_ACCESS_TOKEN: $(PLAYWRIGHT_SERVICE_ACCESS_TOKEN) # Not recommended, use Microsoft Entra ID authentication. 

       inputs:
         azureSubscription: 'testservice' # Service connection used to authenticate this pipeline with Azure to use the service
         scriptType: 'pscore'
         scriptLocation: 'inlineScript'
         inlineScript: npx playwright test --grep "@Regression" -c playwright.service.config.ts --workers=1
         addSpnToEnvironment: true

     - task: PublishPipelineArtifact@1
       displayName: Upload Playwright report
       inputs:
         targetPath: tests/playwright-report/ # update accordingly
         artifact: 'Playwright tests'
         publishLocation: 'pipeline'